# Generated by Django 6.0.4 on 2026-04-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='payouts_ide_merchan_4d8fc8_idx',
            old_name='payouts_ide_merchant_key_80cc30_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='payouts_ide_expires_f51cdf_idx',
            old_name='payouts_ide_expires_56ef38_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='payouts_led_merchan_37f31e_idx',
            old_name='payouts_led_merchant_create_8f074e_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='payouts_led_merchan_0aaa5a_idx',
            old_name='payouts_led_merchant_entry__fbfa7d_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='payouts_led_related_da7f0c_idx',
            old_name='payouts_led_related_entry_9e05ad_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_merchan_9a626f_idx',
            old_name='payouts_pay_merchant_status_4cdce4_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_status_fa602c_idx',
            old_name='payouts_pay_status_update_eb753c_idx',
        ),
    ]
